# Use an official OpenJDK runtime as a parent image
FROM openjdk:17-jdk-slim

# Set the working directory in the container
WORKDIR /app

# Copy the JAR file from the target directory into the container
COPY target/message-0.0.1-SNAPSHOT.jar /app/my-app.jar

# Expose the port that the application runs on
EXPOSE 8080

# Define the command to run your application
ENTRYPOINT ["java","-jar","/app/my-app.jar"]