# Use a base image with Java installed
FROM openjdk:17-jdk-slim

# Set the working directory in the container
WORKDIR /app

# Copy the JAR file from the host to the container
COPY target/emergency.jar app.jar

# Run the JAR file
ENTRYPOINT ["java", "-jar", "app.jar"]
