# Use a base image with Java installed
FROM openjdk:17-jdk-slim

# Set the working directory in the container
WORKDIR /app

# Copy the JAR file from the host to the container
COPY emergency/target/emergency-0.0.1-SNAPSHOT.jar emergency-0.0.1-SNAPSHOT.jar

# Run the JAR file
ENTRYPOINT ["java", "-jar", "emergency-0.0.1-SNAPSHOT.jar"]
