[build]
  # The directory where the Angular build outputs are located
  publish = "dist/my-angular-app"
  
  # The build command for Angular
  command = "ng build --prod"

[[redirects]]
  # Proxy API requests to avoid CORS issues
  from = "https://evented.netlify.app/*"
  to = "https://calculated-bliss.onrender.com/api/events/:splat"
  status = 200
  headers = { 
    "Access-Control-Allow-Origin" = "*",
    "Access-Control-Allow-Methods" = "GET, POST, PUT, DELETE, OPTIONS",
    "Access-Control-Allow-Headers" = "Content-Type, Authorization"
  }

[[redirects]]
  # Redirect all routes to index.html for single-page app
  from = "/*"
  to = "/index.html"
  status = 200
  force = true