[build]
  publish = "dist/e-vented-viewer/browser"
  command = "ng build"

[[redirects]]
  from = "/api/*"
  to = "https://calculated-bliss.onrender.com/:splat"
  status = 200
  force = true

[[headers]]
  for = "https://evented.netlify.app/"
    [headers.values]
    Access-Control-Allow-Origin = "https://evented.netlify.app"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"